DROP TABLE MARKET_ITEM;
CREATE TABLE MARKET_ITEM
(
    ITEM_NO            VARCHAR(20)      NOT NULL COMMENT '아이템번호',
    ITEM_NAME          VARCHAR(20)      NOT NULL COMMENT '아이템이름',
    YESTERDAY_AVG_PRICE DECIMAL(10,2)   DEFAULT 0 NOT NULL COMMENT '전일평균가',
    LAST_PRICE          DECIMAL(10,2)   DEFAULT 0 NOT NULL COMMENT '최근거래가',
    LOWEST_PRICE        DECIMAL(10,2)   DEFAULT 0 NOT NULL COMMENT '최저가',
    BATCH_ID            VARCHAR(12)     NOT NULL COMMENT '배치 ID',

    CONSTRAINT PK_MARKET_ITEM
        PRIMARY KEY (ITEM_NO, BATCH_ID),
    CONSTRAINT FK_MARKET_ITEM_ITEM_NO
        FOREIGN KEY (ITEM_NO, ITEM_NAME) REFERENCES ITEM(ITEM_NO, ITEM_NAME),
    CONSTRAINT FK_MARKET_ITEM_BATCH_ID
        FOREIGN KEY (BATCH_ID) REFERENCES MARKET_BATCH (BATCH_ID)
)
    COMMENT '거래소 아이템';

TRUNCATE MARKET_ITEM;
SELECT * FROM MARKET_ITEM;