DROP TABLE FIRST_CATEGORY;
CREATE TABLE FIRST_CATEGORY(
    FIRST_CATEGORY NUMERIC(10),
    CATEGORY_NAME VARCHAR(20),
    CATEGORY_KOR_NAME VARCHAR(20),

    PRIMARY KEY (FIRST_CATEGORY, CATEGORY_NAME)
)
COMMENT '로스트아크 거래소 첫 번째 카테고리'
;

SELECT * FROM FIRST_CATEGORY;
-- 첫 카테고리 기본값
INSERT INTO FIRST_CATEGORY (CATEGORY_NAME, FIRST_CATEGORY, CATEGORY_KOR_NAME) VALUES ('ALL', '0', '전체');
INSERT INTO FIRST_CATEGORY (CATEGORY_NAME, FIRST_CATEGORY, CATEGORY_KOR_NAME) VALUES ('EQUIPMENT_BOX', '10100', '장비 상자');
INSERT INTO FIRST_CATEGORY (CATEGORY_NAME, FIRST_CATEGORY, CATEGORY_KOR_NAME) VALUES ('AVATAR', '20000', '아바타');
INSERT INTO FIRST_CATEGORY (CATEGORY_NAME, FIRST_CATEGORY, CATEGORY_KOR_NAME) VALUES ('ENGRAVE_BOOK', '40000', '각인서');
INSERT INTO FIRST_CATEGORY (CATEGORY_NAME, FIRST_CATEGORY, CATEGORY_KOR_NAME) VALUES ('REINFORCE_MATERIAL', '50000', '강화재료');
INSERT INTO FIRST_CATEGORY (CATEGORY_NAME, FIRST_CATEGORY, CATEGORY_KOR_NAME) VALUES ('BATTLE_ITEM', '60000', '배틀아이템');
INSERT INTO FIRST_CATEGORY (CATEGORY_NAME, FIRST_CATEGORY, CATEGORY_KOR_NAME) VALUES ('COOKING', '70000', '요리');
INSERT INTO FIRST_CATEGORY (CATEGORY_NAME, FIRST_CATEGORY, CATEGORY_KOR_NAME) VALUES ('LIFE_MATERIAL', '90000', '생활재료');
INSERT INTO FIRST_CATEGORY (CATEGORY_NAME, FIRST_CATEGORY, CATEGORY_KOR_NAME) VALUES ('BOOK_OF_ADVENTURES', '100000', '모험의서');
INSERT INTO FIRST_CATEGORY (CATEGORY_NAME, FIRST_CATEGORY, CATEGORY_KOR_NAME) VALUES ('VOYAGE', '110000', '항해');
INSERT INTO FIRST_CATEGORY (CATEGORY_NAME, FIRST_CATEGORY, CATEGORY_KOR_NAME) VALUES ('PET', '140000', '펫');
INSERT INTO FIRST_CATEGORY (CATEGORY_NAME, FIRST_CATEGORY, CATEGORY_KOR_NAME) VALUES ('VEHICLE', '160000', '탈것');
INSERT INTO FIRST_CATEGORY (CATEGORY_NAME, FIRST_CATEGORY, CATEGORY_KOR_NAME) VALUES ('ETC', '170000', '기타');
INSERT INTO FIRST_CATEGORY (CATEGORY_NAME, FIRST_CATEGORY, CATEGORY_KOR_NAME) VALUES ('JEWEL_CASE', '220000', '보석상자');