DROP TABLE MARKET_ITEM;
CREATE TABLE MARKET_ITEM
(
    NAME                VARCHAR(20)          NOT NULL COMMENT '이름',
    FIRST_CATEGORY      DECIMAL              NOT NULL COMMENT '첫 번째 카테고리',
    SECOND_CATEGORY     DECIMAL              NOT NULL COMMENT '두 번째 카테고리',
    YESTERDAY_AVG_PRICE DECIMAL(5) DEFAULT 0 NOT NULL COMMENT '전일평균가',
    LAST_PRICE          DECIMAL(5) DEFAULT 0 NOT NULL COMMENT '최근거래가',
    LOWEST_PRICE        DECIMAL(5) DEFAULT 0 NOT NULL COMMENT '최저가',
    BATCH_ID            VARCHAR(12)          NOT NULL COMMENT '배치 ID',
    BATCH_DATE          TIMESTAMP            NOT NULL COMMENT '배치일자',
    PRIMARY KEY (NAME, BATCH_ID),
    CONSTRAINT FK_MARKET_ITEM_BATCH_ID
        FOREIGN KEY (BATCH_ID, BATCH_DATE) REFERENCES MARKET_BATCH (BATCH_ID, BATCH_DATE),
    CONSTRAINT FK_MARKET_ITEM_FIRST_CATEGORY
        FOREIGN KEY (FIRST_CATEGORY) REFERENCES FIRST_CATEGORY (FIRST_CATEGORY),
    CONSTRAINT FK_MARKET_ITEM_SECOND_CATEGORY
        FOREIGN KEY (SECOND_CATEGORY) REFERENCES SECOND_CATEGORY (SECOND_CATEGORY)
)
    COMMENT '거래소 아이템';