DROP TABLE MARKET_BATCH;
CREATE TABLE MARKET_BATCH (
    BATCH_ID VARCHAR(12) NOT NULL COMMENT '배치 ID',
    BATCH_DATE TIMESTAMP NOT NULL COMMENT '배치일자',

    PRIMARY KEY PK_MARKET_ITEM (BATCH_ID, BATCH_DATE)
)
COMMENT '로스트아크 거래소 배치';

-- MARKET_BATCH 신규 시퀀스 생성
CALL SP_CREATE_SEQUENCES('MARKET_BATCH');
-- MARKET_BATCH 시퀀스 NEXT_VAL 채번
SELECT FN_NEXT_VAL('MARKET_BATCH') FROM dual;

INSERT INTO MARKET_BATCH (BATCH_ID, BATCH_DATE) VALUES (FN_NEXT_VAL('MARKET_BATCH'), SYSDATE());